name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install sbt
        run: |
          curl -L -o sbt-1.5.5.deb https://dl.bintray.com/sbt/debian/sbt-1.5.5.deb
          sudo dpkg -i sbt-1.5.5.deb
          sudo apt-get update
          sudo apt-get install sbt

      - name: Build project
        run: sbt compile

      - name: Generate SBOM
        run: sbt bomGenerate

      - name: Upload SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: bom.xml
