name: Generate SBOM and Convert to CSV

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install sbt
        run: |
          curl -L -o sbt-1.5.5.zip https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.zip
          unzip sbt-1.5.5.zip
          sudo mv sbt /usr/local/sbt
          echo 'export PATH="/usr/local/sbt/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Add sbt-bom plugin
        run: |
          mkdir -p project
          echo 'addSbtPlugin("io.github.siculo" % "sbt-bom" % "0.3.0")' >> project/plugins.sbt

      - name: Build project
        run: sbt compile

      - name: Generate SBOM
        run: sbt makeBom

      - name: Move and Merge SBOM
        run: |
          mkdir merged_bom
          find . -name "*.bom.xml" -exec mv {} merged_bom/ \;
          cat merged_bom/*.bom.xml > merged_bom/merged_bom.xml

      - name: Convert SBOM to CSV
        run: |
          curl -o xmlstarlet.tar.gz -L http://downloads.sourceforge.net/project/xmlstar/xmlstarlet/1.6.1/xmlstarlet-1.6.1.tar.gz
          tar -xzf xmlstarlet.tar.gz
          cd xmlstarlet-1.6.1
          ./configure
          make
          sudo make install
          cd ..
          xmlstarlet sel -T -t -m "//dependency" -v "artifactId" -o "," -v "version" -n merged_bom/merged_bom.xml > merged_bom/merged_bom.csv

      - name: Upload CSV
        uses: actions/upload-artifact@v2
        with:
          name: csv
          path: merged_bom/merged_bom.csv
