name: Semgrep Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 'adopt@1.11'
          distribution: 'adopt'

      - name: Install Semgrep
        run: curl -L https://semgrep.dev/install.sh | sh

      - name: Run Semgrep
        run: semgrep --config=p/security-audit /path/to/scan --lang=scala
