name: Semgrep Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: "Git :: Checkout"
        uses: actions/checkout@v3

      - name: "SemGrep :: Analysis"
        continue-on-error: true
        run: semgrep ci --exclude-rule yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha --sarif --output=semgrep.sarif
        shell: bash
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: ${{ inputs.rules }} # more at semgrep.dev/explore

      - name: "GitHub Advanced Security :: Upload Sarif"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
          token: ${{ secrets.GH_TOKEN }}
        if: always()
