name: Semgrep Scan

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... Other steps ...

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
